services:
  - type: web
    name: chargeguard-api
    runtime: docker
    repo: https://github.com/amr2883/chargeguard-api
    branch: master
    dockerContext: .
    dockerfilePath: ./Dockerfile
    dockerCommand: "node src/server.js"
    envVars:
      - key: DATABASE_URL
        sync: false
