services:
  - type: web
    name: chargeguard-api
    runtime: docker
    repo: https://huggingface.co/spaces/Amr453/chargeguard-space
    branch: master
    dockerContext: .
    dockerfilePath: ./Dockerfile
    dockerCommand: "node src/app.js"
    envVars:
      - key: DATABASE_URL
        sync: false